name: matrix
on: push
jobs:
  build:
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [12, 14, 16]
        os: [ubuntu-latest, windows-latest]
    steps:
     - name: get code
       uses: actions/checkout@v3
     - name: install Nodejs
       uses: actions/setup-node@v3
       with:
         node-version: ${{ matrix.node-version }}
     - name: install
       run: npm ci
     - name: test
       run: npm test